### ISSUE TITLE
Feature request: Change default behavior to look for `pyproject.toml`, back it up to `pyproject.toml.old`, and write output to `pyporject.toml`

### ISSUE THREAD

**Issue by araichev** [ninoseki/bukowski#4]
That'll probably help the majority of users, so that they just type `bukowski` in their repo for conversion.
Allow the user to override the defaults, of course.

**Comment by ninoseki** [comment]
`bukowski /path/to/pyproject.toml` doesn't overwrite `pyproject.toml` but outputs uv compatible `pyproject.toml` to STDOUT.
You need to set `-f` option for overwriting the file.

**Comment by araichev** [comment]
Yes, i see that option. My suggestion is to change the default behavior as i described above so that the user typically types less.

**Comment by ninoseki** [comment]
`bukowski` for the dry-run. `-f` for overwriting. I think it's enough especially when considering VCS (Git, etc.). Making a backup does not make much sense.
